//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tahorg.RCJoyGUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tahorg.RCJoyGUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Common_Headers_Error {
            get {
                return ResourceManager.GetString("Common_Headers_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string CreateJoystickDialog_CheckJoystick_Error {
            get {
                return ResourceManager.GetString("CreateJoystickDialog_CheckJoystick_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong total bits number, must be multiple of 8.
        /// </summary>
        internal static string CreateJoystickDialog_CheckJoystick_Wrong_total_bits_number__must_be_multiple_of_8 {
            get {
                return ResourceManager.GetString("CreateJoystickDialog_CheckJoystick_Wrong_total_bits_number__must_be_multiple_of_8" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable read fault.
        /// </summary>
        internal static string EEPMapDialog_ReadFault {
            get {
                return ResourceManager.GetString("EEPMapDialog_ReadFault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable write fault.
        /// </summary>
        internal static string EEPMapDialog_WriteFault {
            get {
                return ResourceManager.GetString("EEPMapDialog_WriteFault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        internal static string ParseJoyDialog_ParseJoyDialog_Connected {
            get {
                return ResourceManager.GetString("ParseJoyDialog_ParseJoyDialog_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not connected.
        /// </summary>
        internal static string ParseJoyDialog_ParseJoyDialog_Not_connected {
            get {
                return ResourceManager.GetString("ParseJoyDialog_ParseJoyDialog_Not_connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication error.
        /// </summary>
        internal static string ParseJoyDialog_ReadCom_Communication_error {
            get {
                return ResourceManager.GetString("ParseJoyDialog_ReadCom_Communication_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        internal static string ParseJoyDialog_ReadCom_Complete {
            get {
                return ResourceManager.GetString("ParseJoyDialog_ReadCom_Complete", resourceCulture);
            }
        }
    }
}
